### ISSUE TITLE
Publishing to crates.io

### ISSUE THREAD

**Issue by nyurik** [georust/tilejson#15]
Hi @stepankuzmin , are you the only person who publishes this crate to crates.io? I see that github team `georust:tilejson-publishers` also has that right, and I was wondering if you want me to participate in that process? I do plan to add a number of other features to this crate, possibly some validation code, etc. Thanks!

**Comment by stepankuzmin** [comment]
Hey @nyurik 👋 

Sure, that would be great! I've added you to the [`georust:tilejson-publishers`](https://github.com/orgs/georust/teams/tilejson-publishers/members) team, so you can publish a new release.

**Comment by stepankuzmin** [comment]
Hey @nyurik 👋 

Sure, that would be great! I've added you to the [`georust:tilejson-publishers`](https://github.com/orgs/georust/teams/tilejson-publishers/members) team, so you can publish a new release.
