### ISSUE TITLE
migrate CI to GH actions

### ISSUE THREAD

**Issue by michaelkirk** [georust/tilejson#4]
I noticed you still have a .travis.yml

I believe free CI on travis-ci.org has been canceled since about June. Also, travis-ci recently had a [nasty bug (and a not great response to said bug)](https://twitter.com/peter_szilagyi/status/1437646118700175360).

Almost all of the other georust projects are running on GH actions, would you be interested in migrating? 

I could help with this if you have questions or lack the time.

**Comment by stepankuzmin** [comment]
Hi @michaelkirk! Thanks for noticing, will do in #5
